spring.datasource.url=jdbc:mysql://127.0.0.1:3306/demo_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=41336900Sa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
